### ISSUE TITLE
When using fsdp=true, the error message is the same. Does this not have any effect?

### ISSUE THREAD

**Issue by joytianya** [young-geng/EasyLM#33]
When I use 13b, batch_size=1, an error occurs on v3-8 as follows: 
When using fsdp=true, the error message is the same. Does this not have any effect?

jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Failed to allocate request for 12.50MiB (13107200
B) on device ordinal 0: while running replica 0 and partition 0 of a replicated computation (other replicas
 may have failed as well).

...
--fsdp=True
...

**Comment by young-geng** [comment]
FSDP only reduces memory usage when you have extra DP mesh axis. In your v3-8 case, it is likely you used all the accelerators for model parallelism, so your DP axis is probably already 1. In that case, FSDP will not reduce memory usage.

**Comment by joytianya** [comment]
Yes, I did configure “8,1" indeed.
So, is this(13b) configuration suitable for v3-256?
 
--mp_mesh_dim='32,1' \
or
--mp_mesh_dim='32,8' \

**Comment by young-geng** [comment]
I would recommend `32,1`, as we don't need that much model parallelism for a 13b model. The rest can be saved for data parallelism.

**Comment by joytianya** [comment]
but i try it ， It encountered this error, seems to have happened in the save function. May I ask what is the reason for this?


```shell
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/llama_easylm/EasyLM/EasyLM/models/llama/llama_train.py", line 288, in <module>
    mlxu.run(main)
  File "/home/.local/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/.local/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/llama_easylm/EasyLM/EasyLM/models/llama/llama_train.py", line 240, in main
    save_checkpoint(train_state)
  File "/home/llama_easylm/EasyLM/EasyLM/models/llama/llama_train.py", line 212, in save_checkpoint
    checkpointer.save_all(
File "/home/llama_easylm/EasyLM/EasyLM/checkpoint.py", line 91, in save_all
    self.save_checkpoint(
  File "/home/llama_easylm/EasyLM/EasyLM/checkpoint.py", line 43, in save_checkpoint
    self.save_train_state_to_file(
  File "/home/llama_easylm/EasyLM/EasyLM/checkpoint.py", line 58, in save_train_state_to_file
    value = gather_fns[key](value)
  File "/home/llama_easylm/EasyLM/EasyLM/jax_utils.py", line 95, in gather_fn
    return jax.device_get(jax_gather_fn(tensor))
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Failed to allocate request for 625.00MiB (655360000B) on device ordinal 0: while running replica 0 and partition 0 of a replicated computation (other replicas may have failed as well).
```

**Comment by joytianya** [comment]
more detail
```python
File "/home/.local/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/jax/_src/pjit.py", line 248, in cache_miss
    outs, out_flat, out_tree, args_flat = _python_pjit_helper(
  File "/home/.local/lib/python3.8/site-packages/jax/_src/pjit.py", line 195, in _python_pjit_helper
    out_flat = pjit_p.bind(*args_flat, **params)
  File "/home/.local/lib/python3.8/site-packages/jax/_src/core.py", line 2591, in bind
    return self.bind_with_trace(top_trace, args, params)
  File "/home/.local/lib/python3.8/site-packages/jax/_src/core.py", line 362, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/.local/lib/python3.8/site-packages/jax/_src/core.py", line 816, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/.local/lib/python3.8/site-packages/jax/_src/pjit.py", line 1269, in _pjit_call_impl
    return compiled.unsafe_call(*args)
  File "/home/.local/lib/python3.8/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 1934, in __call__
    results = self.xla_executable.execute_sharded(input_bufs)
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Failed to allocate request for 625.00MiB (655360000B) on device or
dinal 0: while running replica 0 and partition 0 of a replicated computation (other replicas may have failed as well).

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.
```

**Comment by joytianya** [comment]
For TPU pod v3-256, do you have any recommended configuration on 13b? I have tried multiple configurations but they all result in similar errors.

**Comment by young-geng** [comment]
For TPU v3-256 with the 13b model, I recommend using FSDP and use mesh dim `4,1`. I'm able to get batch size 64 with that configuration

**Comment by joytianya** [comment]
Great, I tried several configurations before (8,1) (16,1) (32,1) (64,1), but none of them worked. It turns out that only (4,1) works. Thank you very much for your suggestion.
I also have two small questions:
1. What is the reason why configurations larger than 4 do not work?
2. If it's for 30b and 65b, can batch size be reduced proportionally? For example, can 30b be set to 16 and 65b to 8 and still run normally with mesh dim set at (4,1)?
Thanks again~

**Comment by young-geng** [comment]
I'm also not sure why other configurations do not work on TPU. Maybe TPU-v3s are just too limited in memory. I will try to look into this more.

**Comment by joytianya** [comment]
Thank you for your reply. I will conduct further experiments and provide you with feedback on any new discoveries as soon as possible.

**Comment by joytianya** [comment]
> For TPU v3-256 with the 13b model, I recommend using FSDP and use mesh dim `4,1`. I'm able to get batch size 64 with that configuration

For the updated code, how should 3d mesh dim be configured to achieve the same effect? 
Is the following configuration okay?
```python
...
--mesh_dim='1,64,4'
...
```

**Comment by young-geng** [comment]
Yeah that seems correct. I recommend use FSDP as much as possible instead of MP.

**Comment by joytianya** [comment]
thank you ~
